FROM alpine:3.11
RUN apk add --no-cache gcc mariadb-dev
WORKDIR /rathena
COPY --from=builder:latest /rathena/map-server /rathena/
COPY conf /rathena/conf
COPY db /rathena/db
COPY npc /rathena/npc

CMD ["./map-server"]

